//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.OperacionesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesService.IOperaciones")]
    public interface IOperaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/SumarNumeros", ReplyAction="http://tempuri.org/IOperaciones/SumarNumerosResponse")]
        int SumarNumeros(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/SumarNumeros", ReplyAction="http://tempuri.org/IOperaciones/SumarNumerosResponse")]
        System.Threading.Tasks.Task<int> SumarNumerosAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/RestarNumeros", ReplyAction="http://tempuri.org/IOperaciones/RestarNumerosResponse")]
        int RestarNumeros(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/RestarNumeros", ReplyAction="http://tempuri.org/IOperaciones/RestarNumerosResponse")]
        System.Threading.Tasks.Task<int> RestarNumerosAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/MultiplicarNumeros", ReplyAction="http://tempuri.org/IOperaciones/MultiplicarNumerosResponse")]
        int MultiplicarNumeros(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/MultiplicarNumeros", ReplyAction="http://tempuri.org/IOperaciones/MultiplicarNumerosResponse")]
        System.Threading.Tasks.Task<int> MultiplicarNumerosAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/DividirNumeros", ReplyAction="http://tempuri.org/IOperaciones/DividirNumerosResponse")]
        float DividirNumeros(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/DividirNumeros", ReplyAction="http://tempuri.org/IOperaciones/DividirNumerosResponse")]
        System.Threading.Tasks.Task<float> DividirNumerosAsync(float a, float b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesChannel : PL.OperacionesService.IOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesClient : System.ServiceModel.ClientBase<PL.OperacionesService.IOperaciones>, PL.OperacionesService.IOperaciones {
        
        public OperacionesClient() {
        }
        
        public OperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SumarNumeros(int a, int b) {
            return base.Channel.SumarNumeros(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumarNumerosAsync(int a, int b) {
            return base.Channel.SumarNumerosAsync(a, b);
        }
        
        public int RestarNumeros(int a, int b) {
            return base.Channel.RestarNumeros(a, b);
        }
        
        public System.Threading.Tasks.Task<int> RestarNumerosAsync(int a, int b) {
            return base.Channel.RestarNumerosAsync(a, b);
        }
        
        public int MultiplicarNumeros(int a, int b) {
            return base.Channel.MultiplicarNumeros(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicarNumerosAsync(int a, int b) {
            return base.Channel.MultiplicarNumerosAsync(a, b);
        }
        
        public float DividirNumeros(float a, float b) {
            return base.Channel.DividirNumeros(a, b);
        }
        
        public System.Threading.Tasks.Task<float> DividirNumerosAsync(float a, float b) {
            return base.Channel.DividirNumerosAsync(a, b);
        }
    }
}
